# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      name: Install
    - run: npm run test-single-headless
      name: Test
    - run: npm run test:coveralls
      name: Publish Test Coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.coveralls }}
    - run: npm run lint
      name: Lint
    - run: npm run build
      name: Build
    - name: Write Configuration
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'dist/ng-radio/assets/config/app.config.json'
      env:
        appInsightsInstrumentationKey: ${{ secrets.appinsights_instrumentation_key }}
        authConfig.clientId: ${{ secrets.authconfig_clientid }}
        authConfig.customQueryParams.audience: ${{ secrets.authconfig_audience }}
        authConfig.issuer: ${{ secrets.authconfig_issuer }}
        authConfig.logoutUrl: ${{ secrets.authconfig_logouturl }}
        authConfig.redirectUri: ${{ secrets.authconfig_redirecturi }}
        authConfig.postLogoutRedirectUri: ${{ secrets.authconfig_redirecturi }}
        authConfig.silentRefreshRedirectUri: ${{ secrets.authconfig_silentrefreshredirecturi }}
        corsProxyUrl: ${{ secrets.cors_proxy_url }}
        favoriteStationsApiUrl: ${{ secrets. favorite_stations_api_url }}
        metadataApiUrl: ${{ secrets. metadata_api_url }}
    - name: FTP Deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.0.1
      with:
        ftp_host: ${{ secrets.ftp_host }}
        ftp_username: ${{ secrets.ftp_username }}
        ftp_password: ${{ secrets.ftp_password }}
        local_source_dir: "dist/ng-radio"
        dist_target_dir: "/"
        disable_ssl_certificate_verification: true
        delete: true